# Generated by Django 5.2.3 on 2025-06-26 13:43

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='default-post', editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
