# Generated by Django 5.2.3 on 2025-06-26 15:52

import django.core.validators
import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('posts', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='posts', to='images.image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(error_messages={'blank': 'Title cannot be blank.', 'unique': 'This title already exists. Please use a different one.'}, max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(10, message='Title must be at least 10 characters.'), posts.models.validate_title_length]),
        ),
    ]
