# Generated by Django 5.2.3 on 2025-07-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_images_alter_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='images',
        ),
    ]
