# Generated by Django 5.2.3 on 2025-07-08 15:10
from django.db import migrations

def assign_default_role(apps, schema_editor):
    Role = apps.get_model('roles', 'Role')
    UserProfile = apps.get_model('accounts', 'UserProfile')  # or 'core', wherever it is

    seller_role = Role.objects.get(name='seller')

    # Assign seller role to all profiles where role is not set
    for profile in UserProfile.objects.filter(role__isnull=True):
        profile.role = seller_role
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_role'),
        ('roles', '0002_auto_20250708_1402'),
    ]

    operations = [
        migrations.RunPython(assign_default_role),
    ]
