# Generated by Django 5.2.3 on 2025-07-09 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('make', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='make.make')),
            ],
            options={
                'verbose_name': 'Car Variant',
                'verbose_name_plural': 'Car Variants',
                'ordering': ['make__name', 'name'],
                'unique_together': {('make', 'name')},
            },
        ),
    ]
