# Generated by Django 5.2.3 on 2025-07-09 07:55

import autoslug.fields
import cars.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20250708_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'blank': 'Title cannot be blank.', 'unique': 'This title already exists. Please use a different one.'}, max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(10, message='Title must be at least 10 characters.'), cars.models.validate_title_length])),
                ('detail', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='accounts.userprofile')),
            ],
        ),
    ]
