# Generated by Django 5.2.3 on 2025-07-09 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
        ('variant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='variant.variant'),
        ),
    ]
