# Generated by Django 5.2.3 on 2025-07-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('salvage', 'Salvage'), ('flood', 'Flood'), ('non_accident', 'Non Accident'), ('accident', 'Accident')], default='non_accident', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='engine_starts',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('gas', 'Gas'), ('petrol', 'Petrol')], default='gas', max_length=10),
        ),
        migrations.AddField(
            model_name='car',
            name='has_keys',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AddField(
            model_name='car',
            name='manufacture_year',
            field=models.PositiveIntegerField(default=1970, help_text='Enter the year of manufacture'),
        ),
        migrations.AddField(
            model_name='car',
            name='odometer',
            field=models.PositiveIntegerField(default=0, help_text='Enter mileage in kilometers or miles'),
        ),
    ]
