# Generated by Django 5.2.3 on 2025-07-10 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_car_type_car_engine_starts_car_fuel_type_and_more'),
        ('color', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='color.color'),
        ),
    ]
