# Generated by Django 5.2.3 on 2025-07-10 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.CharField(default='Lahore, PK', help_text='Enter location', max_length=100),
        ),
        migrations.AddField(
            model_name='car',
            name='weight',
            field=models.PositiveIntegerField(default=100, help_text='Enter weight in kg'),
        ),
    ]
