# Generated by Django 5.2.3 on 2025-07-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_location_car_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='auction_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
