# Generated by Django 5.2.3 on 2025-07-08 14:02

from django.db import migrations

def create_roles(apps, schema_editor):
    Role = apps.get_model('roles', 'Role')
    for name in ['seller', 'bidder', 'guest']:
        Role.objects.get_or_create(name=name)

class Migration(migrations.Migration):
    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_roles),
    ]
